package com.gcll.ticketagent.agent;

public enum AgentStepName {
    SUBMITTED,
    PREPROCESS,
    TICKET_EXTRACT,
    TRIAGE_PIPELINE,
    FOLLOW_UP_QUESTION_GENERATE,
    AGENT_PLAN,
    KNOWLEDGE_SEARCH,
    TOOL_SELECTION,
    EVIDENCE_COLLECTION,
    ROOT_CAUSE_ANALYSIS,
    PRIORITY_EVALUATION,
    TEAM_ROUTING,
    SUGGESTION_GENERATION,
    HUMAN_CONFIRM_DECISION,
    WAIT_HUMAN_CONFIRM,
    FINAL
}
