DELETE FROM ops_metric_sample;
DELETE FROM ops_log_sample;
DELETE FROM knowledge_document;

INSERT INTO knowledge_document (id, source_type, source_id, title, content, system_name, module_name, tags)
VALUES
('kd-001', 'SOP', 'sop-pay-callback-001', '支付回调失败处理 SOP',
 '生产环境支付回调 /pay/callback 返回 500 时，先查接口错误日志，检查 payment_callback_log 回调处理状态，检查 MQ 消费积压和死信队列，检查订单补偿任务。若涉及多用户或资金状态不一致，按 P1 处理并进入人工确认。',
 '支付系统', '支付回调', '["支付","回调","500","订单"]'),
('kd-002', 'REDMINE', 'rm-8821', '支付成功订单状态未更新',
 '现象：用户支付成功但订单仍为待支付。原因：回调处理失败或 MQ 消费异常。方案：检查回调日志、订单补偿任务、支付成功事件消费位点。',
 '支付系统', '支付回调', '["订单","待支付","MQ"]'),
('kd-003', 'RUNBOOK', 'rb-payment-oom-001', 'payment-service OOMKilled Runbook',
 '当 payment-service Pod OOMKilled 时，先确认容器内存 limit 与工作集曲线，检查最近发布、批量任务、缓存对象增长和 JVM heap dump。若生产多用户支付失败，先扩容或回滚，再分析泄漏。',
 '支付系统', '支付服务', '["OOM","K8s","内存","Runbook"]'),
('kd-004', 'INCIDENT', 'inc-2026-0412', '支付服务缓存击穿导致内存上涨',
 '历史故障：促销期间支付服务本地缓存未设置最大容量，热点 key 扩散导致 heap usage 持续升高，最终 OOMKilled。处理：限流、回滚缓存策略、补充 Caffeine maximumSize。',
 '支付系统', '支付服务', '["缓存","OOM","促销"]'),
('kd-005', 'SOP', 'sop-db-pool-001', '数据库连接池耗尽排查 SOP',
 'HikariPool 连接不可用或等待线程快速升高时，检查慢 SQL、未关闭连接、事务过长、连接池 maxPoolSize、数据库活跃连接和锁等待。生产核心链路受影响时按 P1 处理。',
 '订单系统', '数据库连接池', '["DB","HikariCP","连接池","Timeout"]'),
('kd-006', 'REDMINE', 'rm-9134', '订单查询慢 SQL 导致连接池耗尽',
 '现象：order-service HikariPool active 达到 50，waiting 线程增加。原因：订单列表查询缺少联合索引，事务持有连接过久。方案：加索引、降低事务范围、临时扩容连接池。',
 '订单系统', '订单查询', '["慢SQL","连接池","索引"]'),
('kd-007', 'SOP', 'sop-mfa-001', 'MFA 重置 SOP',
 'MFA 重置必须先查询用户状态和最近登录风险，需管理员审批后执行。普通账号单用户问题默认 P3；涉及管理员批量无法登录时升级到 P1/P2。',
 '账号系统', 'MFA', '["MFA","账号","权限"]'),
('kd-008', 'RUNBOOK', 'rb-permission-001', '权限开通失败排查 Runbook',
 '权限开通失败先确认用户、角色、租户、审批单状态和权限同步任务。若仅单用户测试环境问题，优先级低；若生产批量权限同步失败，需要升级。',
 '账号系统', '权限', '["权限","审批","同步"]'),
('kd-009', 'INCIDENT', 'inc-2026-0508', '库存扣减成功但订单未更新',
 '数据一致性问题：库存服务扣减成功后订单服务消费失败，导致订单状态未同步。需检查 outbox 表、MQ 死信、补偿任务和幂等消费记录。',
 '订单系统', '数据一致性', '["数据不一致","MQ","补偿"]'),
('kd-010', 'SOP', 'sop-mq-lag-001', 'MQ 消费积压排查 SOP',
 '当支付成功事件或订单事件积压时，检查 consumer lag、死信队列、消费异常日志、实例数和下游数据库耗时。涉及核心交易链路时按 P1。',
 '中间件平台', '消息队列', '["MQ","积压","死信"]'),
('kd-011', 'RUNBOOK', 'rb-cache-timeout-001', 'Redis 缓存超时排查 Runbook',
 'Redis 超时先检查连接池、慢查询、热点 key、大 key、网络抖动和 Redis CPU。若缓存不可用导致核心链路降级失败，需要快速切换降级策略。',
 '基础平台', 'Redis', '["Redis","缓存","超时"]'),
('kd-012', 'ERROR_CODE', 'err-pay-500-callback', '支付回调 500 常见错误码',
 'PAY-CALLBACK-500 通常与签名校验失败、回调幂等冲突、数据库连接异常或 MQ 发布失败有关。需要结合日志 traceId 和 payment_callback_log 状态确认。',
 '支付系统', '支付回调', '["错误码","PAY-CALLBACK-500"]'),
('kd-013', 'SOP', 'sop-test-env-p3', '测试环境单用户故障优先级规则',
 '测试环境、单用户、可绕过且不影响发布窗口的问题一般评为 P3。若阻塞验收或影响发布窗口，可提升到 P2。',
 '通用', '优先级', '["P3","测试环境"]'),
('kd-014', 'INCIDENT', 'inc-2026-0601', '结算任务重复执行导致账务差异',
 '结算批任务重复执行导致账务差异，需立即冻结相关批次，核对流水、幂等表和补偿记录。资金相关数据不一致默认至少 P1 并需要人工确认。',
 '结算系统', '批处理', '["资金","数据不一致","幂等"]'),
('kd-015', 'RUNBOOK', 'rb-no-hit-001', '知识库无命中处理规范',
 '当知识库无相似案例命中时，Agent 必须明确标注无历史来源，转向日志、指标和人工补充信息，不得编造历史案例。',
 '通用', '知识库', '["无命中","可信输出"]'),
('kd-016', 'POSTMORTEM', 'pm-pay-oom-2026-0611', 'payment-service OOM 复盘：本地缓存无上限',
 '复盘结论：payment-service 在促销流量下将风控结果写入本地 Map，未设置 maximumSize 和过期策略，导致 JVM heap 持续增长。监控表现为 container_memory_working_set_mib 20 分钟内从 220Mi 增长到 520Mi，随后 Pod OOMKilled。改进：统一使用 Caffeine，设置 maximumSize、expireAfterWrite，并补充 cache size 指标。',
 '支付系统', '支付服务', '["OOM","payment-service","Caffeine","heap","复盘"]'),
('kd-017', 'RUNBOOK', 'rb-jvm-heap-dump-001', 'JVM Heap Dump 采集 Runbook',
 'Java 服务出现 OutOfMemoryError 时，优先确认是否允许采集 heap dump。若 Pod 即将被 kill，可临时提升内存 limit 或复制流量后采集。分析重点：大对象、集合容量、缓存 key 数量、线程本地变量和最近发布变更。生产 P1 场景先止血，再做 dump 分析。',
 '通用', 'JVM', '["JVM","heap dump","OutOfMemoryError","OOM"]'),
('kd-018', 'SOP', 'sop-k8s-oom-001', 'Kubernetes OOMKilled 排查 SOP',
 'Pod 状态为 OOMKilled 时，检查 lastState.terminated.reason、exitCode=137、容器 limit、working set、重启次数、最近发布和 HPA 扩缩容记录。若业务错误与重启时间吻合，应把 OOM 作为高优先级根因候选。',
 '基础平台', 'Kubernetes', '["K8s","OOMKilled","exitCode137","Pod"]'),
('kd-019', 'ERROR_CODE', 'err-jvm-heap-space', 'java.lang.OutOfMemoryError: Java heap space',
 'Java heap space 表示 JVM 堆内存分配失败。常见原因包括本地缓存无限增长、集合未释放、批处理一次加载过多数据、图片或报文大对象堆积。需要结合 GC 日志、heap dump、内存曲线和最近发布判断。',
 '通用', 'JVM', '["Java heap space","OOM","GC"]'),
('kd-020', 'INCIDENT', 'inc-pay-risk-cache-2026-0529', '支付风控缓存膨胀导致回调延迟',
 '历史故障：payment-service 风控缓存 key 使用 userId+deviceId+orderId 拼接，促销期间 key 基数暴涨，GC 时间升高，支付回调平均耗时从 120ms 增长到 3s。处理：回滚缓存策略，增加 maximumSize 和命中率监控。',
 '支付系统', '支付服务', '["风控","缓存","GC","回调延迟"]'),
('kd-021', 'SOP', 'sop-payment-p1-001', '支付链路 P1 判定 SOP',
 '支付、结算、退款等资金链路在生产环境出现多用户失败、订单状态不一致、资金状态不可确认时默认按 P1 处理。P1 建议必须进入人工确认，不能由 Agent 自动执行恢复动作。',
 '支付系统', '优先级', '["P1","支付","资金","人工确认"]'),
('kd-022', 'RUNBOOK', 'rb-pay-callback-retry-001', '支付回调补偿 Runbook',
 '支付回调失败时，先按 traceId 查询 payment_callback_log，再检查幂等键、签名校验、MQ 发布结果和订单补偿任务。补偿前必须确认第三方支付状态，避免重复入账或重复发货。',
 '支付系统', '支付回调', '["支付回调","补偿","幂等","traceId"]'),
('kd-023', 'INCIDENT', 'inc-pay-callback-mq-2026-0320', '支付回调成功但事件发布失败',
 '历史故障：第三方支付回调处理成功，但 payment_success_event 发布到 MQ 失败，订单状态未更新。定位依据：payment_callback_log=SUCCESS，outbox 表存在未发送记录，consumer 未收到事件。修复：补偿发送 outbox，并加发布失败告警。',
 '支付系统', '支付回调', '["outbox","MQ","支付成功事件","订单状态"]'),
('kd-024', 'ERROR_CODE', 'err-pay-sign-invalid', 'PAY-SIGN-INVALID 签名校验失败',
 'PAY-SIGN-INVALID 表示支付回调签名校验失败，常见于渠道密钥配置错误、回调报文被网关改写、时间戳过期或验签算法版本不一致。需核对渠道配置、原始报文和网关日志。',
 '支付系统', '支付回调', '["签名","验签","支付回调"]'),
('kd-025', 'SOP', 'sop-slow-sql-001', '慢 SQL 排查 SOP',
 '接口延迟升高或连接池等待增加时，先查慢 SQL 日志、执行计划、索引命中、锁等待和事务范围。不要只扩连接池，必须确认是否存在全表扫描、FOR UPDATE 长事务或 N+1 查询。',
 '订单系统', '数据库', '["慢SQL","执行计划","索引","锁等待"]'),
('kd-026', 'RUNBOOK', 'rb-order-list-index-001', '订单列表查询索引 Runbook',
 '订单列表按 user_id、status、created_at 查询时，应优先使用联合索引 idx_orders_user_status_created。若 SQL 只命中 status 单列索引，大促期间容易扫描大量历史订单，拖慢连接池。',
 '订单系统', '订单查询', '["订单列表","联合索引","created_at","status"]'),
('kd-027', 'INCIDENT', 'inc-order-lock-2026-0428', '订单状态批量更新锁等待',
 '历史故障：运营批量更新订单状态时使用 SELECT FOR UPDATE 扫描大量 PENDING 订单，导致锁等待和 HikariPool 耗尽。处理：拆批、补联合索引、缩短事务范围，并限制后台任务并发。',
 '订单系统', '订单查询', '["锁等待","HikariCP","批量更新","事务"]'),
('kd-028', 'ERROR_CODE', 'err-db-lock-wait-timeout', 'DB-LOCK-WAIT-TIMEOUT 锁等待超时',
 'DB-LOCK-WAIT-TIMEOUT 通常由长事务、批量更新、缺失索引或热点行竞争导致。排查顺序：查看 innodb_trx、锁等待链路、慢 SQL、事务开始时间和最近上线任务。',
 '订单系统', '数据库', '["锁等待","长事务","慢SQL"]'),
('kd-029', 'SOP', 'sop-mq-dead-letter-001', '死信队列处理 SOP',
 '发现 MQ 死信时，先抽样查看失败原因，区分参数脏数据、下游超时、幂等冲突和代码异常。资金链路事件不允许直接丢弃，必须记录补偿批次和处理人。',
 '中间件平台', '消息队列', '["死信队列","MQ","补偿","资金"]'),
('kd-030', 'RUNBOOK', 'rb-consumer-lag-001', 'Consumer Lag 排查 Runbook',
 'Consumer lag 持续增长时，检查消费错误率、单条消息耗时、消费者实例数、分区分布、下游数据库延迟和限流策略。若 lag 与核心订单或支付事件相关，需要评估业务影响范围。',
 '中间件平台', '消息队列', '["consumer lag","积压","分区","消费耗时"]'),
('kd-031', 'INCIDENT', 'inc-mq-poison-message-2026-0517', '毒消息导致支付事件消费停滞',
 '历史故障：一条异常支付事件反复消费失败，阻塞同分区后续消息，导致支付成功订单延迟更新。处理：识别毒消息、转入隔离队列、修复字段兼容问题，再补偿消费。',
 '中间件平台', '消息队列', '["毒消息","支付事件","隔离队列","订单延迟"]'),
('kd-032', 'SOP', 'sop-redis-hotkey-001', 'Redis 热 Key 排查 SOP',
 'Redis QPS 或 CPU 突增时，检查 hotkey、bigkey、慢查询、连接数和网络延迟。热点 key 可通过本地短 TTL 缓存、请求合并、分片 key 或降级策略缓解。',
 '基础平台', 'Redis', '["Redis","hotkey","bigkey","CPU"]'),
('kd-033', 'INCIDENT', 'inc-redis-bigkey-2026-0308', '大 Key 删除导致 Redis 延迟抖动',
 '历史故障：运营任务删除包含数十万成员的 Redis Set，大 key 删除阻塞主线程，导致支付风控读取 Redis 超时。处理：使用 UNLINK 异步删除，拆分 key，并加 bigkey 巡检。',
 '基础平台', 'Redis', '["bigkey","UNLINK","延迟抖动","支付风控"]'),
('kd-034', 'RUNBOOK', 'rb-rate-limit-001', '核心接口限流与降级 Runbook',
 '核心接口错误率或耗时升高时，先确认是否触发限流、熔断或降级。支付链路降级要区分查询类、写入类和资金状态类操作，资金状态不明确时不得自动成功返回。',
 '基础平台', '稳定性治理', '["限流","熔断","降级","支付"]'),
('kd-035', 'SOP', 'sop-user-login-failure-001', '用户登录失败排查 SOP',
 '登录失败先区分单用户还是批量，检查账号状态、密码错误次数、MFA、风控拦截、SSO 回调和网关日志。单用户可走普通工单，批量管理员登录失败需要升级。',
 '账号系统', '登录', '["登录失败","MFA","SSO","风控"]'),
('kd-036', 'INCIDENT', 'inc-sso-callback-2026-0407', 'SSO 回调地址配置错误导致批量登录失败',
 '历史故障：SSO provider 回调地址配置为旧域名，导致企业用户批量登录失败。表现：网关 302 后回调 404，account-service 无登录会话。处理：回滚配置并刷新 provider metadata。',
 '账号系统', '登录', '["SSO","回调","登录失败","配置"]'),
('kd-037', 'ERROR_CODE', 'err-auth-mfa-expired', 'AUTH-MFA-EXPIRED 动态验证码过期',
 'AUTH-MFA-EXPIRED 表示 MFA 验证码过期或客户端时间偏差过大。单用户场景优先引导重新绑定或校准时间；批量出现需检查 MFA 服务时钟同步和缓存状态。',
 '账号系统', 'MFA', '["MFA","验证码","时钟同步"]'),
('kd-038', 'SOP', 'sop-settlement-diff-001', '账务差异处理 SOP',
 '账务、结算、退款相关数据出现差异时，先冻结相关批次，保留流水快照，核对支付渠道状态、内部账务流水、幂等表和补偿记录。该类问题默认需要人工确认。',
 '结算系统', '账务', '["账务差异","结算","幂等","人工确认"]'),
('kd-039', 'RUNBOOK', 'rb-idempotency-audit-001', '幂等记录审计 Runbook',
 '怀疑重复执行时，检查 idempotency_key、业务唯一键、outbox 事件、补偿任务和操作审计。若幂等记录缺失，不要直接重放任务，先确认外部系统实际状态。',
 '结算系统', '幂等', '["幂等","重复执行","outbox","补偿"]'),
('kd-040', 'POSTMORTEM', 'pm-settlement-duplicate-2026-0601', '结算任务重复执行复盘',
 '复盘结论：结算任务在 worker 超时后被恢复扫描重复拉起，但原 worker 实际仍在执行，幂等表写入晚于外部调用，导致账务差异。改进：DB lease 续期、外部调用前写执行意图、补偿任务加唯一约束。',
 '结算系统', '批处理', '["结算","重复执行","DB lease","幂等"]'),
('kd-041', 'FAQ', 'faq-priority-routing-001', '优先级与团队路由常见规则',
 '支付链路多用户失败优先支付研发组；订单查询慢和连接池耗尽优先订单研发组并协同 DBA；Redis、MQ、Kubernetes 资源问题协同基础平台；账号登录和 MFA 问题优先账号研发组。',
 '通用', '路由', '["团队路由","优先级","支付","订单","基础平台"]'),
('kd-042', 'RUNBOOK', 'rb-agent-source-bound-001', 'Agent 来源约束 Runbook',
 'Agent 输出根因和处置建议时，必须优先引用 SOP、Runbook、Incident、Error Code 或 Postmortem。若只有模型推断而无来源，应该降低置信度并提示人工补查。',
 '通用', 'Agent治理', '["RAG","来源约束","可信输出"]'),
('kd-043', 'SOP', 'sop-agent-human-gate-001', 'Agent 人工确认触发 SOP',
 '以下场景必须触发人工确认：P1/P0、资金状态不明确、需要执行恢复动作、根因置信度低、RAG 无命中但建议影响生产、工具调用失败较多。',
 '通用', 'Agent治理', '["HITL","人工确认","P1","低置信度"]'),
('kd-044', 'INCIDENT', 'inc-k8s-restart-loop-2026-0219', 'K8s 重启循环导致接口间歇失败',
 '历史故障：服务启动后读取配置失败，Pod 进入 CrashLoopBackOff，网关出现间歇性 502。排查依据：restart count 快速增加、lastState reason=Error、应用日志包含配置缺失。',
 '基础平台', 'Kubernetes', '["CrashLoopBackOff","502","配置缺失"]'),
('kd-045', 'ERROR_CODE', 'err-http-502-upstream', 'HTTP-502-UPSTREAM 网关上游异常',
 'HTTP 502 通常表示网关无法从上游服务获得有效响应，常见原因包括 Pod 重启、连接拒绝、服务发现异常、上游超时或网关配置错误。需要结合网关日志和服务实例状态判断。',
 '基础平台', '网关', '["502","网关","上游异常"]');

INSERT INTO knowledge_document (id, source_type, source_id, title, content, system_name, module_name, tags)
VALUES
('kd-046', 'RUNBOOK', 'rb-ruoyi-ai-docker-001', 'RuoYi-AI Docker 后端排障 Runbook',
 'RuoYi-AI 后端容器 ruoyi-ai-backend 暴露 26039:6039，依赖 MySQL(ruoyi-ai-mysql)、Redis(ruoyi-ai-redis)、Weaviate、MinIO。后端异常时先查看 logs/ruoyi-ai.log 或容器日志，再检查数据库连接、Redis 连接、向量库连接和对象存储配置。',
 'ruoyi-ai', '后端服务', '["RuoYi-AI","Docker","ruoyi-ai-backend","Runbook"]'),
('kd-047', 'SOP', 'sop-ruoyi-ai-login-001', 'RuoYi-AI 登录失败处理 SOP',
 '管理端登录失败时，先确认后端 26039 端口健康、验证码配置、Sa-Token/JWT 配置、MySQL 用户表、Redis token 缓存和网关代理。若日志出现 RedisConnectionFailureException，优先检查 Redis 容器和 SPRING_DATA_REDIS_HOST。',
 'ruoyi-ai', '认证登录', '["登录失败","Sa-Token","JWT","Redis","验证码"]'),
('kd-048', 'SOP', 'sop-ruoyi-ai-mysql-001', 'RuoYi-AI MySQL 连接异常 SOP',
 'RuoYi-AI 使用 dynamic-datasource 连接 MySQL，Docker compose 内部地址应为 mysql:3306，库名通常为 ruoyi-ai-agent。若日志出现 Communications link failure、Access denied、Unknown database，需要检查容器健康状态、账号密码、库名和初始化 SQL。',
 'ruoyi-ai', 'MySQL', '["MySQL","dynamic-datasource","Communications link failure","Unknown database"]'),
('kd-049', 'SOP', 'sop-ruoyi-ai-redis-001', 'RuoYi-AI Redis 连接异常 SOP',
 'RuoYi-AI 登录态、缓存、限流等依赖 Redis。Docker compose 内部地址应为 redis:6379，一键部署对外端口是 26379。若后端日志出现 RedisConnectionFailureException、Unable to connect to Redis server，应检查 Redis 容器、网络、端口和密码配置。',
 'ruoyi-ai', 'Redis', '["Redis","RedisConnectionFailureException","缓存","登录态"]'),
('kd-050', 'RUNBOOK', 'rb-ruoyi-ai-weaviate-001', 'RuoYi-AI Weaviate 向量库排障 Runbook',
 'RuoYi-AI 支持 Weaviate/Milvus/Qdrant。本地 Docker 一键部署 Weaviate 端口为 28080，应用配置 vector-store.weaviate.host 默认 127.0.0.1:6038 时可能与容器地址不一致。知识库/RAG 异常时检查向量库类型、host、collection 和容器健康。',
 'ruoyi-ai', '向量库', '["Weaviate","RAG","向量库","知识库"]'),
('kd-051', 'INCIDENT', 'inc-ruoyi-ai-redis-2026-0702', 'RuoYi-AI Redis 未启动导致登录失败',
 '演示故障：ruoyi-ai-redis 容器停止后，管理端登录接口返回 500，后端日志出现 RedisConnectionFailureException 或 connection refused。处理：恢复 Redis 容器，确认 SPRING_DATA_REDIS_HOST=redis，必要时清理错误 token 缓存后重试。',
 'ruoyi-ai', '认证登录', '["Redis","登录失败","Docker","500"]'),
('kd-052', 'INCIDENT', 'inc-ruoyi-ai-mysql-2026-0702', 'RuoYi-AI MySQL 初始化库名不一致',
 '演示故障：MySQL 容器健康但后端启动失败，日志出现 Unknown database ruoyi-ai-agent 或 Access denied。原因通常是 compose 环境变量 MYSQL_DATABASE、初始化脚本创建库名、应用 JDBC URL 三者不一致。',
 'ruoyi-ai', 'MySQL', '["MySQL","Unknown database","初始化脚本","Docker"]'),
('kd-053', 'ERROR_CODE', 'err-ruoyi-ai-500-login', 'RuoYi-AI 登录接口 500',
 'RuoYi-AI 登录接口 500 需要优先查看后端 ERROR 日志。常见根因包括 Redis 不可用、MySQL 不可用、验证码/租户配置异常、Sa-Token 配置异常和网关代理到后端失败。',
 'ruoyi-ai', '认证登录', '["500","登录接口","ERROR"]'),
('kd-054', 'POSTMORTEM', 'pm-ruoyi-ai-docker-network-2026-0702', 'RuoYi-AI Docker 网络配置复盘',
 '复盘结论：容器内服务互联应使用 compose service name，例如 mysql、redis、backend，而不是宿主机 localhost。应用在容器内访问 127.0.0.1 会指向自身容器，容易导致 MySQL/Redis/Weaviate 连接失败。',
 'ruoyi-ai', 'Docker网络', '["Docker","localhost","service name","网络"]'),
('kd-055', 'FAQ', 'faq-ruoyi-ai-service-map-001', 'RuoYi-AI 服务与端口速查',
 'RuoYi-AI 一键部署常见端口：管理端 25666，用户端 25137，后端 26039->6039，MySQL 23306->3306，Redis 26379->6379，Weaviate 28080，MinIO 29000/29090。Agent 排障时按后端、数据库、缓存、向量库、对象存储顺序收集证据。',
 'ruoyi-ai', '服务拓扑', '["端口","Docker","服务拓扑","排障"]');

INSERT INTO ops_log_sample (id, system_name, service_name, module_name, environment, level, occurred_at, trace_id, message, tags)
VALUES
('log-001', '支付系统', 'payment-service', '支付服务', 'prod', 'ERROR', '2026-06-11 10:23:15', 'trace-pay-oom-001',
 'Java heap space: OutOfMemoryError; Pod payment-service-7b8c9d4-x2k9 terminated with OOMKilled exit code 137; memory limit 512Mi, usage before kill 524Mi.',
 '["OOM","K8s","payment-service"]'),
('log-002', '支付系统', 'payment-service', '支付服务', 'prod', 'WARN', '2026-06-11 10:21:42', 'trace-pay-oom-001',
 'Local cache paymentRiskCache size increased to 245000 entries after promotion traffic spike.',
 '["cache","memory"]'),
('log-003', '订单系统', 'order-service', '数据库连接池', 'prod', 'WARN', '2026-06-11 10:15:32', 'trace-order-db-001',
 'HikariPool-1 - Connection is not available, request timed out after 30000ms; active=50 idle=0 waiting=23 max=50.',
 '["HikariCP","connection-timeout"]'),
('log-004', '订单系统', 'order-service', '订单查询', 'prod', 'ERROR', '2026-06-11 10:15:34', 'trace-order-db-001',
 'Slow SQL detected: SELECT * FROM orders WHERE status=PENDING FOR UPDATE cost=28450ms.',
 '["slow-sql","lock"]'),
('log-005', '支付系统', 'payment-callback', '支付回调', 'prod', 'ERROR', '2026-06-11 10:05:11', 'trace-pay-cb-001',
 '/pay/callback returned 500; payment_callback_log status=FAILED; publish payment_success_event failed.',
 '["callback","500","MQ"]'),
('log-006', '账号系统', 'account-service', 'MFA', 'prod', 'INFO', '2026-06-11 09:05:11', 'trace-mfa-001',
 'MFA reset request created for user u-8831; waiting admin approval.',
 '["MFA","approval"]'),
('log-007', '结算系统', 'settlement-job', '批处理', 'prod', 'ERROR', '2026-06-11 02:31:00', 'trace-settle-001',
 'Duplicate settlement batch detected: batchNo=SETTLE-20260610 already processed, idempotency record missing.',
 '["settlement","idempotency"]');

INSERT INTO ops_metric_sample (id, system_name, service_name, metric_name, environment, occurred_at, metric_value, unit, labels, status)
VALUES
('metric-001', '支付系统', 'payment-service', 'container_memory_working_set_mib', 'prod', '2026-06-11 10:20:00', 412, 'Mi', '{"pod":"payment-service-7b8c9d4-x2k9"}', 'rising'),
('metric-002', '支付系统', 'payment-service', 'container_memory_working_set_mib', 'prod', '2026-06-11 10:21:00', 467, 'Mi', '{"pod":"payment-service-7b8c9d4-x2k9"}', 'rising'),
('metric-003', '支付系统', 'payment-service', 'container_memory_working_set_mib', 'prod', '2026-06-11 10:22:00', 501, 'Mi', '{"pod":"payment-service-7b8c9d4-x2k9"}', 'near_limit'),
('metric-004', '支付系统', 'payment-service', 'container_memory_working_set_mib', 'prod', '2026-06-11 10:23:00', 524, 'Mi', '{"pod":"payment-service-7b8c9d4-x2k9","limit":"512Mi"}', 'oom_killed'),
('metric-005', '订单系统', 'order-service', 'hikaricp_connections_active', 'prod', '2026-06-11 10:12:00', 30, 'count', '{"pool":"HikariPool-1","max":"50"}', 'normal'),
('metric-006', '订单系统', 'order-service', 'hikaricp_connections_active', 'prod', '2026-06-11 10:13:00', 38, 'count', '{"pool":"HikariPool-1","max":"50"}', 'rising'),
('metric-007', '订单系统', 'order-service', 'hikaricp_connections_active', 'prod', '2026-06-11 10:14:00', 45, 'count', '{"pool":"HikariPool-1","max":"50"}', 'high'),
('metric-008', '订单系统', 'order-service', 'hikaricp_connections_active', 'prod', '2026-06-11 10:15:00', 50, 'count', '{"pool":"HikariPool-1","max":"50","waiting":"23"}', 'exhausted'),
('metric-009', '支付系统', 'payment-callback', 'http_server_errors', 'prod', '2026-06-11 10:05:00', 37, 'count', '{"uri":"/pay/callback","status":"500"}', 'error_spike'),
('metric-010', '结算系统', 'settlement-job', 'duplicate_batch_count', 'prod', '2026-06-11 02:31:00', 2, 'count', '{"batchNo":"SETTLE-20260610"}', 'duplicate');
